// mock-data.js — shared content for the mobile refinement exploration.
window.WEDDING_MOCK = {
  settings: { venueName: 'Vodárenské múzeum', currency: 'EUR', weddingDate: '2026-09-12', budgetTarget: 9000 },
  daysUntil: 71,
  dailyLine: 'Popoludní sa dotiahnu detaily a Magulová kapitola sa blíži.',
  tasks: [
    { id: 't1', title: 'Kedy?', category: 'Planning', phase: 'High', priority: 'HIGH', status: 'DONE', deadline: '15. 1.', notes: 'Vyhodnotiť piatok vs sobotu a potvrdiť dátum čo najskôr.' },
    { id: 't2', title: 'Sála', category: 'Venue', phase: 'High', priority: 'HIGH', status: 'IN_PROGRESS', deadline: '20. 7.', notes: 'Vodárenské múzeum — 1050 €, 8 hod + deň vopred na chystanie.' },
    { id: 't3', title: 'Kostol & kňaz', category: 'Ceremony', phase: 'High', priority: 'HIGH', status: 'TODO', deadline: '25. 7.', notes: 'Br. Lukáš, Hobbit? Františkáni? Spýtať sa Niki.' },
    { id: 't4', title: 'Obed — Reštika', category: 'Food', phase: 'High', priority: 'HIGH', status: 'TODO', deadline: '1. 8.', notes: 'Kde a rezervovať, aj kto to vybaví.' },
    { id: 't5', title: 'Obrúčky', category: 'Jewelry', phase: 'High', priority: 'MEDIUM', status: 'TODO', deadline: '10. 8.', notes: 'Teta Žanet. Nenápadne zapojiť zlato.' },
    { id: 't6', title: 'Kytica', category: 'Flowers', phase: 'High', priority: 'MEDIUM', status: 'TODO', deadline: '20. 8.', notes: 'Vybrať a objednať svadobnú kyticu.' },
    { id: 't7', title: 'Vlasy a mejkap', category: 'Beauty', phase: 'High', priority: 'MEDIUM', status: 'TODO', deadline: null, notes: 'Ladiť termín a človeka, ktorý to urobí.' },
    { id: 't8', title: 'Namiesto koláča zmrzka', category: 'Food', phase: 'Low', priority: 'LOW', status: 'DONE', deadline: null, notes: 'Zmrzka namiesto klasického koláča — rozhodnuté.' },
    { id: 't9', title: 'Darčeky', category: 'Decisions', phase: 'Low', priority: 'LOW', status: 'BLOCKED', deadline: null, notes: 'Nebude zoznam darov.' },
    { id: 't10', title: 'Fotenie', category: 'Photo', phase: 'High', priority: 'HIGH', status: 'TODO', deadline: '5. 8.', notes: 'Kossey deal: fotenie — obrad — prvé tance.' },
    { id: 't11', title: 'Auto — Majo', category: 'Logistics', phase: 'Medium', priority: 'MEDIUM', status: 'TODO', deadline: '15. 8.', notes: 'Dohodnúť auto s Majom.' },
  ],
  guests: [
    { id: 'g1', name: 'Mama', familyGroup: 'Angelika', attendance: 'YES', dinner: true, party: false },
    { id: 'g2', name: 'Veronika', familyGroup: 'Angelika', attendance: 'YES', dinner: true, party: true },
    { id: 'g3', name: 'Rasťa', familyGroup: 'Angelika', attendance: 'YES', dinner: true, party: true },
    { id: 'g4', name: 'Babka', familyGroup: 'Angelika', attendance: 'YES', dinner: true, party: true },
    { id: 'g5', name: 'Tato', familyGroup: 'Tomáš', attendance: 'YES', dinner: true, party: true },
    { id: 'g6', name: 'Marek', familyGroup: 'Tomáš', attendance: 'YES', dinner: true, party: true },
    { id: 'g7', name: 'Dedo', familyGroup: 'Tomáš', attendance: 'YES', dinner: true, party: false },
    { id: 'g8', name: 'Hanka', familyGroup: 'Party', attendance: 'MAYBE', dinner: false, party: true },
    { id: 'g9', name: 'Kossey', familyGroup: 'Party', attendance: 'YES', dinner: false, party: true },
    { id: 'g10', name: 'Filip', familyGroup: 'Party', attendance: 'MAYBE', dinner: false, party: true },
    { id: 'g11', name: 'Sani', familyGroup: 'Party', attendance: 'NO', dinner: false, party: false },
  ],
  expenses: [
    { id: 'e1', title: 'Záloha — Vodárenské múzeum', category: 'Venue', amount: 400, currency: 'EUR', isPaid: true, vendor: 'Vodárenské múzeum' },
    { id: 'e2', title: 'Obrúčky', category: 'Jewelry', amount: 620, currency: 'EUR', isPaid: false, vendor: 'Teta Žanet' },
    { id: 'e3', title: 'Kytica', category: 'Flowers', amount: 180, currency: 'EUR', isPaid: false, vendor: null },
    { id: 'e4', title: 'Fotograf — Kossey', category: 'Photo', amount: 750, currency: 'EUR', isPaid: true, vendor: 'Kossey' },
    { id: 'e5', title: 'Auto — Majo', category: 'Logistics', amount: 120, currency: 'EUR', isPaid: false, vendor: 'Majo' },
  ],
};
